export enum USER_GROUP {
  ADMIN = 'Admin',
  DATA_MANAGEMENT = 'DataManagement',
  GENERAL = 'General',
  OPERATIONS_MISSION_ADVISOR = 'OperationsMissionAdvisor',
  QRG_ADMIN = 'QRGAdmin',
  QRG_DATA_MANAGEMENT = 'QRGDataManagement',
  FP_ADMIN = 'FPAdmin',
  FP_DATA_MANAGEMENT = 'FPDataManagement',
  MOBILE_RELEASE = 'MobileAdmin',
  NOTIFICATIONS = 'Notifications',
  NOTIFICATIONS_ADMIN = 'Notifications.Admin',
  SYSTEM_ADMIN = 'SystemAdmin',
  FEATURE_NOTES = 'FeatureNotes',
  UA_USER = 'UAUser',
  UWA_MARKETING = 'MarketingUser',
  SECURITY = 'Security.Beta',
  USER_MANAGEMENT = 'UserManagement',
  USER_MANAGEMENT_ADMIN = 'UserManagementAdmin',
  USER_MANAGEMENT_GROUPS = 'UserManagement.Groups',
  RETAIL_DATA = 'RetailData',
  CUSTOMER_CARE = 'uwa.uvgo.cc',
  VENDOR_MANAGEMENT_ADMIN = 'Vendor.Admin',
}
