export enum EDITOR_TYPES {
  TEXT_FIELD = 'InputText',
  DROPDOWN = 'Dropdown',
  AUTO_COMPLETE = 'AutoComplete',
  RADIO = 'Radio',
  CHECKBOX = 'Checkbox',
  DATE_TIME = 'DateTime',
  DATE = 'Date',
  TIME = 'Time',
  THREAT_LEVEL = 'ThreatLevel',
  BUTTON = 'Button',
  RICH_TEXT_EDITOR = 'Editor',
  GRID = 'Grid',
  LINK = 'Link',
  SELECT_CONTROL = 'SelectControl',
  LABEL = 'Label',
  CHIP_INPUT = 'ChipInput',
  CUSTOM_COMPONENT = 'CustomComponent',
  FREE_SOLO_CHIP_INPUT = 'FreeSoloChipInput',
  MARKDOWN_EDITOR = 'MarkDownEditor',
  SWITCH = 'Switch'
}
