export const templatePalette = {
  shadowColor: {
    default: '',
    hovered: '',
    focused: '',
    active: '',
    disabled: '',
    success: '',
    warning: '',
    error: '',
  },
  borderColor: {
    default: '',
    hovered: '',
    focused: '',
    active: '',
    disabled: '',
    success: '',
    warning: '',
    error: '',
  },
  backgroundColor: {
    default: '',
    hovered: '',
    focused: '',
    active: '',
    disabled: '',
    success: '',
    warning: '',
    error: '',
  },
  textColor: {
    default: '',
    hovered: '',
    focused: '',
    active: '',
    disabled: '',
    success: '',
    warning: '',
    error: '',
  },
};
