export enum USER_STATUS {
    ACTIVE = 'ACTIVE',
    DEPROVISIONED = 'DEPROVISIONED',
    LOCKED_OUT = 'LOCKED_OUT',
    PASSWORD_EXPIRED = 'PASSWORD_EXPIRED',
    PROVISIONED = 'PROVISIONED',
    RECOVERY = 'RECOVERY',
    PENDING_IMPORT = 'PENDING_IMPORT',
    DELETED = 'DELETED',
}