export const fields = {
  crewVaccinationRequirement: {
    fields: {
      vaccinePrivileges: { label: 'Vaccine Privileges', value: [] },
      isVaccinationRequired: { label: 'Vaccine Required' },
      vaccinationType: { label: 'Vaccination Type' },
      vaccineManufacturers: { label: 'Accepted Vaccine Manufacturer', value: [] },
      vaccinationRequirementIssuedCountries: { label: 'Vaccination Country of Issue', value: [] },
      leadTime: { label: 'Minimum Time Since Vaccine Series Completion', rules: 'numeric' },
      expirationDays: { label: 'Vaccine Expiration', rules: 'numeric' },
      isBoosterRequired: { label: 'Booster Required' },
      isDocumentationRequired: { label: 'Documentation Required' },
      documentationRequirements: { label: 'Documentation Requirements', rules: 'string|between:1,500' },
      additionalInformation: { label: 'Other Information', rules: 'string|between:1,500' },
      isInherited: { label: 'Same as Parent', rules: 'boolean' },
      boosterVaccineExpiration: { label: 'Booster Vaccine Expiration', rules: 'integer|min:1|max:365' },
      vaccineBoosterManufacturers: { label: 'Accepted Vaccine Manufacturer', value: [] },
      isBoosterExpiry : { label: 'Booster Expiry' },
      boosterExemptions: { label: 'Exemptions for booster', rules: 'string|between:1,100' },
    },
  },
  passengerVaccinationRequirement: {
    fields: {
      vaccinePrivileges: { label: 'Vaccine Privileges', value: [] },
      isVaccinationRequired: { label: 'Vaccine Required' },
      vaccinationType: { label: 'Vaccination Type' },
      vaccineManufacturers: { label: 'Accepted Vaccine Manufacturer', value: [] },
      vaccinationRequirementIssuedCountries: { label: 'Vaccination Country of Issue', value: [] },
      leadTime: { label: 'Minimum Time Since Vaccine Series Completion', rules: 'numeric' },
      expirationDays: { label: 'Vaccine Expiration', rules: 'numeric' },
      isBoosterRequired: { label: 'Booster Required' },
      isDocumentationRequired: { label: 'Documentation Required' },
      documentationRequirements: { label: 'Documentation Requirements', rules: 'string|between:1,500' },
      isAgeExemption: { label: 'Age Exemption' },
      age: { label: 'Age', rules: 'integer|min:1' },
      additionalInformation: { label: 'Other Information', rules: 'string|between:1,500' },
      isInherited: { label: 'Same as Parent', rules: 'boolean' },
      boosterVaccineExpiration: { label: 'Booster Vaccine Expiration', rules: 'integer|min:1|max:365' },
      vaccineBoosterManufacturers: { label: 'Accepted Vaccine Manufacturer', value: [] },
      isBoosterExpiry : { label: 'Booster Expiry' },
      boosterExemptions: { label: 'Exemptions for booster', rules: 'string|between:1,100' },
    },
  },
};
